{
 "title": "Libvirt (KVM) v3 - messi",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total[5m])",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Per-cpu average usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total[5m])",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Memory Usage (GB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_memory_usage_bytes/1000000000",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Memory Usage (GB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes/1000000000",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "Block devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Read requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_requests_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_file }})"
    }
   ]
  },
  {
   "title": "Write requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_write_requests_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_file }})"
    }
   ]
  },
  {
   "title": "Read bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_bytes_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_file }})"
    }
   ]
  },
  {
   "title": "Write bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_write_bytes_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_file }})"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Packets received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_packets_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_bridge }})"
    }
   ]
  },
  {
   "title": "Packets transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_packets_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_bridge }})"
    }
   ]
  },
  {
   "title": "Receive bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_bytes_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_bridge }})"
    }
   ]
  },
  {
   "title": "Transmit bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_bytes_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_bridge }})"
    }
   ]
  },
  {
   "title": "Receive errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_errors_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_bridge }})"
    }
   ]
  },
  {
   "title": "Receive drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_drops_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_bridge }})"
    }
   ]
  },
  {
   "title": "Transmit errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_errors_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_bridge }})"
    }
   ]
  },
  {
   "title": "Transmit drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_drops_total[5m])",
     "legendFormat": "{{ domain }}: {{ target_device }} ({{ source_bridge }})"
    }
   ]
  }
 ]
}